<?php
/**
 * Created by IntelliJ IDEA.
 * User: XingHuo
 * Date: 15/10/1
 * Time: 下午4:02
 */

class CONSTFILE {
    CONST USER_INTEGRAL = 1;
    CONST USER_GOLD_COIN = 2;
    CONST USER_SILVER_COIN = 3;
    CONST USER_PRESTIGE = 4;
    CONST USER_PRESTIGE_VALUE = 10;

    const CHANGE_LOG_COUNT_TYPE_LV3 = 1;//邀请的大神第一次到达LV3
    const CHANGE_LOG_COUNT_TYPE_5000 = 2;//5000兑换
    const CHANGE_LOG_COUNT_TYPE_ANSWER_30 = 3;//连续回答30天得问题
    const CHANGE_LOG_COUNT_TYPE_ZAN = 4;//赞超过20
    const CHANGE_LOG_COUNT_TYPE_ANSWER_PROBLEM = 5;//赞超过20
    const CHANGE_LOG_COUNT_TYPE_INTEGRAL_TOP = 6;//积分排行榜
    const CHANGE_LOG_COUNT_TYPE_REGISTER = 7;//积分排行榜
    const CHANGE_LOG_COUNT_TYPE_CLICK_ZAN = 8;//用户点赞
    const CHANGE_LOG_COUNT_TYPE_CLICK_COLLECTION = 9;//用户点收藏
    const CHANGE_LOG_COUNT_TYPE_CLICK_COMMENT = 10;//用户发表评论
    const CHANGE_LOG_COUNT_TYPE_CLICK_USER_WATCH = 11;//用户关注大神
    const CHANGE_LOG_COUNT_TYPE_CLICK_USER_SHARE = 12;//用户分享
    const CHANGE_LOG_COUNT_TYPE_CLICK_EMAIL_ACTIVE = 13;//用户邮箱激活

    CONST USER_TASK_FIRST_GOD_LV3 = 1;//大神第一次到达LV3
    CONST USER_TASK_GOD_5000 = 2;//每5k银币 奖励 威望
    CONST USER_TASK_GOD_ANSWER_QUESTION = 3;//每5k银币 奖励 威望
    CONST USER_TASK_SHARE_QQ = 4;//qq 分享任务
    CONST USER_TASK_SHARE_QQZ = 5;//qqz 分享任务
    CONST USER_TASK_SHARE_SINA = 6;//sina 分享任务
    CONST USER_TASK_GOD_ANSWER_QUESTION_VALUE = 30;//连续回答任务满30天


    const USER_SILVER_CHANGE_PRESTIGE_VALUE = 5000; //满多少银币 可以兑换威望

    const USER_ACTION_SILVER_REGISTER_VALUE = 200;//用户注册 奖励银币值
    const USER_ACTION_ZAN_INTEGRAL_VALUE = 10;//用户点赞积分增加值
    const USER_ACTION_COLLECTION_PROBLEM_INTEGRAL_VALUE = 10;//用户收藏积分增加值
    const USER_ACTION_COMMENT_PROBLEM_INTEGRAL_VALUE = 30;//用户评论积分增加值
    const USER_ACTION_USER_WATCH_INTEGRAL_VALUE = 10;//用户关注大神积分增加值

    const USER_ACTION_COMMENT_PROBLEM_SILVER_COIN_VALUE = 20;//用户评论银币增加值
}